apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator.git
    path: example/prometheus-operator-crds
    targetRevision: v0.72.0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
