apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kubelet
  namespace: monitoring
spec:
  endpoints:
    - port: https
      scheme: HTTPS
      path: /metrics
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      k8s-app: kubelet
