resources:
  - namespace.yaml
  - vm-operator.yaml
  - vmcluster.yaml
  - grafana.yaml
  - grafana-ingress.yaml
  - vm-ingress.yaml
  - kube-state-metrics.yaml
  - kube-state-scrape.yaml
  - node-exporter.yaml
  - node-exporter-scrape.yaml
  - kubelet-scrape.yaml
  - kube-apiserver-scrape.yaml
  - ingress-nginx-scrape.yaml
