apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vm
  namespace: monitoring
spec:
  retentionPeriod: "1"

  vmstorage:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "16Gi"

  vmselect:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    cacheMountPath: /select-cache
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "8Gi"

  vminsert:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
