apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vm
  namespace: monitoring
spec:
  retentionPeriod: "1"

  #  NODO DE ALMACENAMIENTO
  vmstorage:
    replicaCount: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "16Gi"

  #  NODO DE CONSULTA
  vmselect:
    replicaCount: 1
    cacheMountPath: /select-cache
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "8Gi"

  #  NODO DE INGESTA
  vminsert:
    replicaCount: 1
