apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vm
  namespace: monitoring

spec:
  retentionPeriod: "1"

  #  === VM AGENT (scraping) ===
  agent:
    replicaCount: 1
    scrapeInterval: 15s
    remoteWrite:
      - url: http://vminsert-vm.monitoring.svc.cluster.local:8480/insert/0/prometheus
    serviceScrapeSelector:
      matchLabels: {}
    podScrapeSelector:
      matchLabels: {}
    nodeScrapeSelector:
      matchLabels: {}
    scrapeConfigSelector:
      matchLabels: {}

  #  === VM STORAGE ===
  vmstorage:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    topologySpreadConstraints: []
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "8Gi"

  #  === VM SELECT ===
  vmselect:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    topologySpreadConstraints: []
    cacheMountPath: /select-cache
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: longhorn
          resources:
            requests:
              storage: "8Gi"

  #  === VM INSERT ===
  vminsert:
    replicaCount: 1
    nodeSelector:
      node.longhorn.io/enable-default-disk: "true"
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    topologySpreadConstraints: []
