apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alberto-blanco-garcia/infra-argocd.git
    targetRevision: HEAD
    path: storage
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
